import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:yaml/yaml.dart';

void main() {
  late YamlMap workflow;

  setUpAll(() {
    final f = File('.github/workflows/release.yml');
    if (!f.existsSync()) {
      fail('.github/workflows/release.yml missing.');
    }
    workflow = loadYaml(f.readAsStringSync()) as YamlMap;
  });

  test('release workflow triggers on tag push', () {
    final push = workflow['on']['push'] as YamlMap;
    final tags = (push['tags'] as YamlList).map((t) => t as String).toList();
    expect(tags, contains('v*'));
  });

  test('release workflow runs fastlane play_upload (which lives in fastlane/Fastfile)', () {
    final jobs = workflow['jobs'] as YamlMap;
    final buildJob = jobs['build-and-publish'] as YamlMap;
    final steps = buildJob['steps'] as YamlList;
    final hasFastlaneStep = steps.any((s) {
      final run = s['run'];
      return run is String && run.contains('fastlane play_upload');
    });
    expect(hasFastlaneStep, isTrue);
  });

  test('release workflow uploads to the internal track by default', () {
    final jobs = workflow['jobs'] as YamlMap;
    final buildJob = jobs['build-and-publish'] as YamlMap;
    final steps = buildJob['steps'] as YamlList;
    // The Play Console upload step is gated on is_prerelease != 'true', i.e.
    // it runs for stable tags. The Fastfile (in fastlane/) is responsible
    // for naming the track; the release workflow only triggers the upload.
    final hasUploadStep = steps.any((s) {
      final run = s['run'];
      return run is String && run.contains('fastlane play_upload');
    });
    expect(hasUploadStep, isTrue,
        reason: 'Stable tags must trigger fastlane play_upload.');
  });

  test('release workflow skips Play Console upload for rc/beta tags', () {
    final jobs = workflow['jobs'] as YamlMap;
    final buildJob = jobs['build-and-publish'] as YamlMap;
    final steps = buildJob['steps'] as YamlList;
    final hasSkipStep = steps.any((s) {
      final name = s['name'];
      final ifCond = s['if'];
      final run = s['run'];
      return name is String &&
          name.toLowerCase().contains('skip play console') &&
          ifCond is String &&
          ifCond.contains('is_prerelease') &&
          run is String;
    });
    expect(hasSkipStep, isTrue);
  });

  test('release workflow checks for all required secrets before doing any work', () {
    final jobs = workflow['jobs'] as YamlMap;
    final buildJob = jobs['build-and-publish'] as YamlMap;
    final steps = buildJob['steps'] as YamlList;
    final checkStep = steps.firstWhere((s) {
      final id = s['id'];
      return id == 'check-secrets';
    }, orElse: () => null);
    expect(checkStep, isNotNull);

    final run = checkStep['run'] as String;
    for (final secret in [
      'ANDROID_KEYSTORE_BASE64',
      'KEY_ALIAS',
      'KEY_PASSWORD',
      'STORE_PASSWORD',
      'PLAY_SUPPLY_JSON_KEY',
    ]) {
      expect(run, contains(secret));
    }
  });

  test('release workflow masks keystore contents from logs', () {
    final jobs = workflow['jobs'] as YamlMap;
    final buildJob = jobs['build-and-publish'] as YamlMap;
    final steps = buildJob['steps'] as YamlList;
    // No step should `cat` the key.properties contents to stdout.
    for (final step in steps) {
      final run = step['run'];
      if (run is! String) continue;
      expect(run, isNot(contains('cat android/key.properties')),
          reason: 'cat-ing key.properties would leak secrets to logs.');
    }
  });

  test('release workflow uses the gradlew generated by the bootstrap step', () {
    final jobs = workflow['jobs'] as YamlMap;
    final buildJob = jobs['build-and-publish'] as YamlMap;
    final steps = buildJob['steps'] as YamlList;
    expect(
      steps.any((s) =>
          (s as YamlMap)['name'] ==
          'Bootstrap Android project (Generates gradlew)'),
      isTrue,
    );
  });

  test('release workflow checks for existing attachments before re-uploading',
      () {
    final jobs = workflow['jobs'] as YamlMap;
    final buildJob = jobs['build-and-publish'] as YamlMap;
    final steps = buildJob['steps'] as YamlList;
    final checkStep = steps.firstWhere((s) {
      final id = s['id'];
      return id == 'check-existing';
    }, orElse: () => null);
    expect(checkStep, isNotNull,
        reason:
            'release.yml must include a `check-existing` step for idempotent re-runs.');
  });

  test('Attach step is gated by the skip_attach output', () {
    final jobs = workflow['jobs'] as YamlMap;
    final buildJob = jobs['build-and-publish'] as YamlMap;
    final steps = buildJob['steps'] as YamlList;
    final attachStep = steps.firstWhere((s) {
      final uses = s['uses'];
      return uses is String && uses.startsWith('softprops/action-gh-release');
    }, orElse: () => null);
    expect(attachStep, isNotNull);
    final ifCond = attachStep['if'] as String;
    expect(ifCond, contains('check-existing'));
    expect(ifCond, contains('skip_attach'));
  });
}
